out_dir : './experiments/toys/test_experiment/'
dimensions : [1, 2, 3, 4, 5]
num_objectives : 1
num_samples : 1000
noise_variance : 0.01
factor_lengthscale : 2
gamma : 0.3
gp_hypers: 
    outputscale: 1.
n_max: 15
